export const surpriseMePrompts = [
  "A surreal underwater cityscape with neon-lit jellyfish floating among skyscrapers.",
  "A whimsical forest where trees are made of candy canes and lollipops, and chocolate rivers flow between them.",
  "An enchanted garden at twilight with fireflies illuminating the path to a hidden fairy castle.",
  "A futuristic metropolis where flying cars zoom past holographic billboards showcasing exotic destinations.",
  "A magical library filled with floating books and staircases that lead to different realms with each turn.",
  "A steampunk-inspired universe where clockwork creatures roam across vast, rusty landscapes.",
  "A mystical mountain peak shrouded in mist, with ancient ruins perched precariously on its cliffs.",
  "A space station orbiting a distant planet, with alien creatures and futuristic technology bustling within its corridors.",
  "A post-apocalyptic wasteland reclaimed by nature, with mutated flora and fauna thriving among the ruins of civilization.",
  "An alternate dimension where gravity works in reverse, causing buildings to hang upside down from the sky.",
  "A mystical forest where ancient spirits dwell among towering trees adorned with glowing runes.",
  "A bustling marketplace in a desert oasis, with colorful tents and merchants selling exotic goods.",
  "A secret garden hidden within the heart of a labyrinth, filled with enchanted flowers and whimsical creatures.",
  "A celestial city floating among the clouds, with angelic beings soaring through the sky.",
  "An abandoned space station overrun by nature, with vines creeping through its corridors and wildlife reclaiming its spaces.",
  "A cyberpunk cityscape illuminated by neon lights, with hovercars zipping through the streets and towering skyscrapers looming overhead.",
  "A fantastical carnival with magical rides and attractions, where dreams come to life after dark.",
  "A parallel universe where dinosaurs still roam the Earth, coexisting with modern technology.",
  "A haunted mansion shrouded in fog, with ghostly apparitions lurking in its shadows.",
  "A futuristic underwater colony with bioluminescent sea creatures and advanced technology.",
  "A time-traveling adventure through different historical eras, from ancient civilizations to futuristic worlds.",
  "A cosmic phenomenon where galaxies collide and stars are born, painting the universe with vibrant colors.",
  "A floating island paradise with waterfalls cascading into crystal-clear lagoons and tropical forests teeming with exotic wildlife.",
  "An enchanted winter wonderland with ice palaces and snow-covered forests inhabited by magical creatures.",
  "A cityscape overtaken by vegetation, with skyscrapers entwined in vines and towering trees rising through the streets.",
  "A parallel dimension where dreams become reality, with surreal landscapes and fantastical creatures.",
  "A journey through the cosmos aboard a spaceship, exploring distant planets and encountering alien civilizations.",
  "A fairytale castle atop a mountain peak, surrounded by lush valleys and sparkling waterfalls.",
  "A digital realm where pixels come to life, with virtual landscapes and fantastical creatures.",
  "A quest through a labyrinthine dungeon filled with traps, puzzles, and mythical monsters.",
  "A tranquil lakeside retreat nestled in the heart of a serene forest, with mist rising from the water at dawn.",
  "A cosmic library containing the knowledge of the universe, with ancient tomes and holographic displays illuminating its halls.",
  "A fantastical journey aboard a flying ship through the clouds, with winged creatures guiding the way.",
  "An underwater kingdom ruled by mermaids and sea dragons, with coral palaces and vibrant marine life.",
  "A hidden temple hidden deep within a jungle, guarded by ancient spirits and filled with mysterious artifacts.",
  "A journey through the dreamscape, where reality shifts and morphs into surreal landscapes and abstract forms.",
  "A steampunk world powered by clockwork mechanisms and steam engines, with airships sailing through the skies.",
  "A cosmic ballet performed by celestial bodies, with planets and stars dancing in perfect harmony.",
  "A cybernetic jungle where nature and technology intertwine, with robotic animals and mechanical plants.",
  "A parallel dimension where magic is real, with wizards and sorcerers wielding powerful spells and incantations.",
];
